apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-auth-deployment
spec:
  selector:
    matchLabels:
      app: myapp-auth
  template:
    metadata:
      labels:
        app: myapp-auth
    spec:
      containers:
      - name: myapp-auth-container
        image: hritik2345/stream-service-authentication:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"

          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        envFrom:
            - secretRef:
                name: mysecret
