apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.8.3
          ports:
            - name: plaintext
              containerPort: 9092
            - name: controller
              containerPort: 9093

          # Load all env vars from the Secret
          envFrom:
            - secretRef:
                name: kafka-secret

          resources:
            requests:
              memory: "768Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"

          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data

          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 60
            periodSeconds: 20

      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: kafka-data