# k8s/kafka_volume.yaml

apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv
  labels:
    app: kafka
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/kafka-data
  claimRef:
    namespace: default
    name: kafka-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-data
  labels:
    app: kafka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi