name: auth-pipeline

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout codewsw
        uses: actions/checkout@v3

      # 2. Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # 3. Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build and push Docker image
       
       
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/stream-service-authentication:latest
            ${{ secrets.DOCKER_USERNAME }}/stream-service-authentication:${{ github.sha }}
       
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG10 }}" | base64 -d > ~/.kube/config


      
      - name: Delete
        run: |
          kubectl delete -f k8s/kafka_volume.yaml
          kubectl delete -f k8s/kafka_deployment.yaml
          kubectl delete -f k8s/kafka_services.yaml
          kubectl delete -f k8s/redis_services.yaml
          kubectl delete -f k8s/services.yaml
          kubectl delete -f k8s/deployment.yaml

      - name: Apply Kafka and Redis
        run: |
          kubectl apply -f k8s/kafka_volume.yaml

          # 3. Service — should exist before the pod starts
          kubectl apply -f k8s/kafka_services.yaml

          # 4. Deployment last
          kubectl apply -f k8s/kafka_deployment.yaml

          kubectl apply -f k8s/redis_services.yaml
           

      - name: Wait for Kafka to be ready
        run: |
          echo "Waiting for Kafka deployment..."
          kubectl rollout status deployment/kafka --timeout=120s
          echo "Kafka rolled out, waiting for pod to be ready..."
          kubectl wait --for=condition=ready pod \
            --selector=app=kafka \
            --timeout=120s
          echo "Kafka pod ready, giving extra buffer..."
          sleep 15
          echo "Kafka ready!"
      
      - name: Wait 2 for Kafka to be ready
        run: |
          echo "Waiting for Kafka deployment..."
          kubectl rollout status deployment/kafka --timeout=120s
          echo "Kafka rolled out, waiting for pod to be ready..."
          kubectl wait --for=condition=ready pod \
            --selector=app=kafka \
            --timeout=120s
          echo "Kafka pod ready, giving extra buffer..."
          sleep 15
          echo "Kafka ready!"

      # 10. Apply Kubernetes manifests
      - name: Apply Kubernetes manifests

        run: |
          
          kubectl apply -f k8s/services.yaml
          kubectl apply -f k8s/deployment.yaml
